package view;

// Victor Machado
import javax.swing.table.DefaultTableModel;
import model.bean.*;
import model.dao.*;
import connection.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.ParseException;
import javax.swing.JOptionPane;
import javax.swing.SpinnerModel;
import javax.swing.SpinnerNumberModel;
import javax.swing.text.MaskFormatter;

public class TelaInicial extends javax.swing.JFrame {

    public TelaInicial() {
        initComponents();
        this.setLocationRelativeTo(null);
        setResizable(false);
        this.setTitle("Página inicial - SISMAC");
        readJTable();

        try {
            MaskFormatter dateMask = new MaskFormatter("####/##/##");
            dateMask.install(txtClientBirthday);
        } catch (ParseException ex) {

        }
        Total.setText("0");
        DefaultTableModel modelovenda = (DefaultTableModel) VendaTabela.getModel();
        modelovenda.setNumRows(0);
    }

    private void readJTable() {
        DefaultTableModel modelo = (DefaultTableModel) TabelaProdutos.getModel();
        modelo.setNumRows(0);

        ProdutoDAO produtoDao = new ProdutoDAO();

        for (Produto p : produtoDao.read()) {
            modelo.addRow(new Object[]{
                p.getId(),
                p.getName(),
                p.getPrice(),
                p.getStorage(),});

            ComboProdutos.addItem(p.toString());
        }

        DefaultTableModel modelouser = (DefaultTableModel) tabelaUsuarios.getModel();
        modelouser.setNumRows(0);

        UsuarioDAO usuarioDao = new UsuarioDAO();

        for (Usuario u : usuarioDao.read()) {
            modelouser.addRow(new Object[]{
                u.getId(),
                u.getName(),
                u.getLogin(),
                u.getPassword(),});
        }

        DefaultTableModel modelocliente = (DefaultTableModel) tabelaClientes.getModel();
        modelocliente.setNumRows(0);

        ClienteDAO clienteDao = new ClienteDAO();

        for (Cliente c : clienteDao.read()) {
            modelocliente.addRow(new Object[]{
                c.getId(),
                c.getName(),
                c.getPhonenumber(),
                c.getBirthdate(),
                c.getEmail(),});
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Tabs = new javax.swing.JTabbedPane();
        PanelInicial = new javax.swing.JPanel();
        PanelProdutos = new javax.swing.JPanel();
        EditProduto = new javax.swing.JButton();
        DeleteProduto = new javax.swing.JButton();
        CreateProduto = new javax.swing.JButton();
        TxtProduto = new javax.swing.JTextField();
        TxtPreco = new javax.swing.JTextField();
        TxtEstoque = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        TabelaProdutos = new javax.swing.JTable();
        PanelUsuario = new javax.swing.JPanel();
        TxtUsername = new javax.swing.JTextField();
        editUsuario = new javax.swing.JButton();
        deleteUsuario = new javax.swing.JButton();
        addUsuario = new javax.swing.JButton();
        TxtUserPass = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaUsuarios = new javax.swing.JTable();
        TxtUserLogin = new javax.swing.JTextField();
        PanelVendas = new javax.swing.JPanel();
        ComboProdutos = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        QtdProduto = new javax.swing.JSpinner();
        addVenda = new javax.swing.JButton();
        TotalLabel = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        VendaTabela = new javax.swing.JTable();
        endVenda = new javax.swing.JButton();
        Total = new javax.swing.JLabel();
        deleteVenda = new javax.swing.JButton();
        PanelCliente = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txtClientName = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtClientMail = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtClientePhone = new javax.swing.JTextField();
        addCliente = new javax.swing.JButton();
        editCliente = new javax.swing.JButton();
        deleteCliente = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaClientes = new javax.swing.JTable();
        txtClientBirthday = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(0, 0));

        Tabs.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Tabs.setPreferredSize(new java.awt.Dimension(530, 530));

        PanelInicial.setAutoscrolls(true);

        javax.swing.GroupLayout PanelInicialLayout = new javax.swing.GroupLayout(PanelInicial);
        PanelInicial.setLayout(PanelInicialLayout);
        PanelInicialLayout.setHorizontalGroup(
            PanelInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 539, Short.MAX_VALUE)
        );
        PanelInicialLayout.setVerticalGroup(
            PanelInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1537, Short.MAX_VALUE)
        );

        Tabs.addTab("Pagina Inicial", PanelInicial);

        EditProduto.setText("Editar");
        EditProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditProdutoActionPerformed(evt);
            }
        });

        DeleteProduto.setText("Excluir o item selecionado");
        DeleteProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteProdutoActionPerformed(evt);
            }
        });

        CreateProduto.setText("Cadastrar");
        CreateProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateProdutoActionPerformed(evt);
            }
        });

        jLabel6.setText(" Produto:");

        jLabel7.setText(" Preço:");

        jLabel8.setText(" Estoque:");

        TabelaProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "id", "name", "price", "storage"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(TabelaProdutos);

        javax.swing.GroupLayout PanelProdutosLayout = new javax.swing.GroupLayout(PanelProdutos);
        PanelProdutos.setLayout(PanelProdutosLayout);
        PanelProdutosLayout.setHorizontalGroup(
            PanelProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelProdutosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PanelProdutosLayout.createSequentialGroup()
                        .addGroup(PanelProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelProdutosLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(PanelProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TxtProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(PanelProdutosLayout.createSequentialGroup()
                                        .addGap(197, 197, 197)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TxtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PanelProdutosLayout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addComponent(CreateProduto)
                                .addGap(29, 29, 29)
                                .addComponent(EditProduto)
                                .addGap(37, 37, 37)
                                .addComponent(DeleteProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PanelProdutosLayout.createSequentialGroup()
                                .addGap(142, 142, 142)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TxtEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 59, Short.MAX_VALUE)))
                .addContainerGap())
        );
        PanelProdutosLayout.setVerticalGroup(
            PanelProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelProdutosLayout.createSequentialGroup()
                .addGroup(PanelProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelProdutosLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(PanelProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(TxtProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(PanelProdutosLayout.createSequentialGroup()
                        .addContainerGap(40, Short.MAX_VALUE)
                        .addComponent(TxtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)))
                .addGroup(PanelProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CreateProduto)
                    .addComponent(EditProduto)
                    .addComponent(DeleteProduto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(796, 796, 796))
        );

        Tabs.addTab("Produtos", PanelProdutos);

        PanelUsuario.setAutoscrolls(true);

        editUsuario.setText("Editar");
        editUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editUsuarioActionPerformed(evt);
            }
        });

        deleteUsuario.setText("Excluir o usuário selecionado");
        deleteUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteUsuarioActionPerformed(evt);
            }
        });

        addUsuario.setText("Cadastrar");
        addUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addUsuarioActionPerformed(evt);
            }
        });

        jLabel3.setText("Nome do Usuário:");

        jLabel4.setText("Senha:");

        jLabel9.setText("Login:");

        tabelaUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "id", "name", "login", "password"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelaUsuarios);

        javax.swing.GroupLayout PanelUsuarioLayout = new javax.swing.GroupLayout(PanelUsuario);
        PanelUsuario.setLayout(PanelUsuarioLayout);
        PanelUsuarioLayout.setHorizontalGroup(
            PanelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelUsuarioLayout.createSequentialGroup()
                        .addGroup(PanelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelUsuarioLayout.createSequentialGroup()
                                .addGap(95, 95, 95)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TxtUserPass, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PanelUsuarioLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TxtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(98, 98, 98)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TxtUserLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(44, 44, 44))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelUsuarioLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 519, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(PanelUsuarioLayout.createSequentialGroup()
                        .addComponent(addUsuario)
                        .addGap(65, 65, 65)
                        .addComponent(editUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(deleteUsuario)
                        .addGap(37, 37, 37))))
        );
        PanelUsuarioLayout.setVerticalGroup(
            PanelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelUsuarioLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(PanelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(TxtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelUsuarioLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(PanelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TxtUserLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))))
                .addGap(10, 10, 10)
                .addGroup(PanelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtUserPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(11, 11, 11)
                .addGroup(PanelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addUsuario)
                    .addGroup(PanelUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(editUsuario)
                        .addComponent(deleteUsuario)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1086, Short.MAX_VALUE))
        );

        Tabs.addTab("Usuários", PanelUsuario);

        ComboProdutos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ComboProdutosItemStateChanged(evt);
            }
        });

        jLabel2.setText("Quantidade");

        QtdProduto.setModel(new javax.swing.SpinnerNumberModel());

        addVenda.setText("Adicionar");
        addVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addVendaActionPerformed(evt);
            }
        });

        TotalLabel.setBackground(java.awt.SystemColor.text);
        TotalLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        TotalLabel.setText("Total: R$");
        TotalLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        VendaTabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "Produto", "Preço", "Quantidade"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(VendaTabela);

        endVenda.setText("Finalizar Venda");
        endVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                endVendaActionPerformed(evt);
            }
        });

        Total.setBackground(java.awt.SystemColor.text);
        Total.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Total.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        deleteVenda.setText("Retirar o item");
        deleteVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteVendaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelVendasLayout = new javax.swing.GroupLayout(PanelVendas);
        PanelVendas.setLayout(PanelVendasLayout);
        PanelVendasLayout.setHorizontalGroup(
            PanelVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelVendasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelVendasLayout.createSequentialGroup()
                        .addGroup(PanelVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(QtdProduto, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ComboProdutos, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(addVenda)
                        .addGap(26, 26, 26))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelVendasLayout.createSequentialGroup()
                        .addComponent(deleteVenda)
                        .addGap(18, 18, 18)))
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelVendasLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(PanelVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelVendasLayout.createSequentialGroup()
                        .addComponent(endVenda)
                        .addGap(154, 154, 154))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelVendasLayout.createSequentialGroup()
                        .addComponent(TotalLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Total, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42))))
        );
        PanelVendasLayout.setVerticalGroup(
            PanelVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelVendasLayout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(ComboProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(PanelVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelVendasLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel2))
                    .addGroup(PanelVendasLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(addVenda)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(QtdProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deleteVenda)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(PanelVendasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Total, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TotalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(endVenda)
                .addGap(1081, 1081, 1081))
        );

        Tabs.addTab("Venda", PanelVendas);

        jLabel10.setText("Nome:");

        jLabel11.setText("Email:");

        jLabel12.setText("Data de Nascimento:");

        jLabel13.setText("Telefone:");

        addCliente.setText("Cadastrar Cliente");
        addCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addClienteActionPerformed(evt);
            }
        });

        editCliente.setText("Editar");
        editCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editClienteActionPerformed(evt);
            }
        });

        deleteCliente.setText("Excluir Cliente");
        deleteCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteClienteActionPerformed(evt);
            }
        });

        tabelaClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "id", "name", "phone_number", "birth_date", "email"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tabelaClientes);

        javax.swing.GroupLayout PanelClienteLayout = new javax.swing.GroupLayout(PanelCliente);
        PanelCliente.setLayout(PanelClienteLayout);
        PanelClienteLayout.setHorizontalGroup(
            PanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 539, Short.MAX_VALUE)
            .addGroup(PanelClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addCliente)
                    .addGroup(PanelClienteLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(PanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelClienteLayout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtClientName, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PanelClienteLayout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtClientBirthday, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(20, 20, 20)
                .addGroup(PanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(PanelClienteLayout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(PanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtClientMail)
                            .addComponent(txtClientePhone, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelClienteLayout.createSequentialGroup()
                        .addComponent(editCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                        .addComponent(deleteCliente)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        PanelClienteLayout.setVerticalGroup(
            PanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelClienteLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(PanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtClientName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(txtClientMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(txtClientePhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtClientBirthday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addCliente)
                    .addComponent(editCliente)
                    .addComponent(deleteCliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1077, Short.MAX_VALUE))
        );

        Tabs.addTab("Clientes", PanelCliente);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Tabs, javax.swing.GroupLayout.DEFAULT_SIZE, 563, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(Tabs, javax.swing.GroupLayout.PREFERRED_SIZE, 563, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        Tabs.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addVendaActionPerformed
        // TODO add your handling code here:
        DefaultTableModel modelo = (DefaultTableModel) VendaTabela.getModel();
        String produto = ComboProdutos.getSelectedItem().toString();
        ProdutoDAO produtoDao = new ProdutoDAO();
        double price = 0;
        for (Produto p : produtoDao.read()) {
            if (p.getName().equals(produto)) {
                price = p.getPrice();
            }
        }
        modelo.addRow(new Object[]{
            ComboProdutos.getSelectedItem(),
            price,
            QtdProduto.getValue(),});
        double qtd = Double.parseDouble(QtdProduto.getValue().toString());
        double total = Double.parseDouble(Total.getText()) + price * qtd;
        Total.setText(String.valueOf(total));
    }//GEN-LAST:event_addVendaActionPerformed

    private void DeleteProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteProdutoActionPerformed
        // TODO add your handling code here:
        ProdutoDAO dao = new ProdutoDAO();
        DefaultTableModel modelo = (DefaultTableModel) TabelaProdutos.getModel();
        int row = TabelaProdutos.getSelectedRow();
        int col = modelo.findColumn("id");
        Produto novoProduto = new Produto();
        novoProduto.setId(Integer.parseInt(modelo.getValueAt(row, col).toString()));

        dao.delete(novoProduto);
        readJTable();
    }//GEN-LAST:event_DeleteProdutoActionPerformed

    private void EditProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditProdutoActionPerformed
        // TODO add your handling code here:
        Produto novoProduto = new Produto();
        ProdutoDAO dao = new ProdutoDAO();

        novoProduto.setName(TxtProduto.getText());
        novoProduto.setPrice(Double.parseDouble(TxtPreco.getText()));
        novoProduto.setStorage(Integer.parseInt(TxtEstoque.getText()));

        String produto = TxtProduto.getText();
        for (Produto p : dao.read()) {
            if (p.getName().equals(produto)) {
                novoProduto.setId(p.getId());
            }
        }
        dao.update(novoProduto);
        readJTable();
    }//GEN-LAST:event_EditProdutoActionPerformed

    private void addUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addUsuarioActionPerformed
        // TODO add your handling code here:
        Usuario novoUsuario = new Usuario();
        UsuarioDAO dao = new UsuarioDAO();

        novoUsuario.setName(TxtUsername.getText());
        novoUsuario.setLogin(TxtUserLogin.getText());
        novoUsuario.setPassword(TxtUserPass.getText());

        dao.create(novoUsuario);
        readJTable();
    }//GEN-LAST:event_addUsuarioActionPerformed

    private void addClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addClienteActionPerformed
        // TODO add your handling code here:
        Cliente novoCliente = new Cliente();
        ClienteDAO dao = new ClienteDAO();

        novoCliente.setName(txtClientName.getText());
        novoCliente.setEmail(txtClientMail.getText());
        novoCliente.setPhonenumber(txtClientePhone.getText());
        novoCliente.setBirthdate(txtClientBirthday.getText());

        dao.create(novoCliente);
        readJTable();
    }//GEN-LAST:event_addClienteActionPerformed

    private void CreateProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateProdutoActionPerformed
        // TODO add your handling code here:
        Produto novoProduto = new Produto();
        ProdutoDAO dao = new ProdutoDAO();

        novoProduto.setName(TxtProduto.getText());
        novoProduto.setPrice(Double.parseDouble(TxtPreco.getText()));
        novoProduto.setStorage(Integer.parseInt(TxtEstoque.getText()));

        dao.create(novoProduto);
        readJTable();
    }//GEN-LAST:event_CreateProdutoActionPerformed

    private void editUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editUsuarioActionPerformed
        // TODO add your handling code here:
        Usuario novoUsuario = new Usuario();
        UsuarioDAO dao = new UsuarioDAO();

        novoUsuario.setName(TxtUsername.getText());
        novoUsuario.setLogin(TxtUserLogin.getText());
        novoUsuario.setPassword(String.valueOf(TxtUserPass.getPassword()));

        String usuario = TxtUsername.getText();
        for (Usuario p : dao.read()) {
            if (p.getName().equals(usuario)) {
                novoUsuario.setId(p.getId());
            }
        }

        dao.update(novoUsuario);
        readJTable();
    }//GEN-LAST:event_editUsuarioActionPerformed

    private void deleteUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteUsuarioActionPerformed
        // TODO add your handling code here:
        UsuarioDAO dao = new UsuarioDAO();
        DefaultTableModel modelo = (DefaultTableModel) tabelaUsuarios.getModel();
        int row = tabelaUsuarios.getSelectedRow();
        int col = modelo.findColumn("id");
        Usuario novoUsuario = new Usuario();
        novoUsuario.setId(Integer.parseInt(modelo.getValueAt(row, col).toString()));

        dao.delete(novoUsuario);
        readJTable();
    }//GEN-LAST:event_deleteUsuarioActionPerformed

    private void editClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editClienteActionPerformed
        // TODO add your handling code here:
        Cliente novoCliente = new Cliente();
        ClienteDAO dao = new ClienteDAO();

        novoCliente.setName(txtClientName.getText());
        novoCliente.setEmail(txtClientMail.getText());
        novoCliente.setPhonenumber(txtClientePhone.getText());
        novoCliente.setBirthdate(txtClientBirthday.getText());

        String cliente = txtClientName.getText();
        for (Cliente p : dao.read()) {
            if (p.getName().equals(cliente)) {
                novoCliente.setId(p.getId());
            }
        }
        dao.update(novoCliente);
        readJTable();
    }//GEN-LAST:event_editClienteActionPerformed

    private void deleteClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteClienteActionPerformed
        // TODO add your handling code here:
        ClienteDAO dao = new ClienteDAO();
        DefaultTableModel modelo = (DefaultTableModel) tabelaClientes.getModel();
        int row = tabelaClientes.getSelectedRow();
        int col = modelo.findColumn("id");
        Cliente novoCliente = new Cliente();
        novoCliente.setId(Integer.parseInt(modelo.getValueAt(row, col).toString()));

        dao.delete(novoCliente);
        readJTable();
    }//GEN-LAST:event_deleteClienteActionPerformed

    private void ComboProdutosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ComboProdutosItemStateChanged
        // TODO add your handling code here:
        String produto = ComboProdutos.getSelectedItem().toString();
        ProdutoDAO produtoDao = new ProdutoDAO();
        int storage = 0;
        for (Produto p : produtoDao.read()) {
            if (p.getName().equals(produto)) {
                storage = p.getStorage();
            }
        }
        SpinnerNumberModel sm = new SpinnerNumberModel(0, 0, storage, 1.0);
        QtdProduto.setModel(sm);
    }//GEN-LAST:event_ComboProdutosItemStateChanged

    private void endVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_endVendaActionPerformed
        // TODO add your handling code here:
        DefaultTableModel modelo = (DefaultTableModel) VendaTabela.getModel();
        int colP = modelo.findColumn("Produto");
        int colQtd = modelo.findColumn("Quantidade");

        for (int i = 0; i < VendaTabela.getRowCount(); i++) {
            String nome = VendaTabela.getValueAt(i, colP).toString();
            double qtd1 = Double.parseDouble(VendaTabela.getValueAt(i, colQtd).toString());
            int qtd = (int) qtd1;
            ProdutoDAO produtoDao = new ProdutoDAO();
            Produto novo = new Produto();
            for (Produto p : produtoDao.read()) {
                if (p.getName().equals(nome)) {
                    novo = p;
                    novo.setStorage(p.getStorage() - qtd);
                    produtoDao.setstorage(novo);
                }
            }
        }
        modelo.setNumRows(0);
        Total.setText("0");
        readJTable();
    }//GEN-LAST:event_endVendaActionPerformed

    private void deleteVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteVendaActionPerformed
        // TODO add your handling code here:
        DefaultTableModel modelo = (DefaultTableModel) VendaTabela.getModel();
        int row = VendaTabela.getSelectedRow();
        modelo.removeRow(row);
    }//GEN-LAST:event_deleteVendaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboProdutos;
    private javax.swing.JButton CreateProduto;
    private javax.swing.JButton DeleteProduto;
    private javax.swing.JButton EditProduto;
    private javax.swing.JPanel PanelCliente;
    private javax.swing.JPanel PanelInicial;
    private javax.swing.JPanel PanelProdutos;
    private javax.swing.JPanel PanelUsuario;
    private javax.swing.JPanel PanelVendas;
    private javax.swing.JSpinner QtdProduto;
    private javax.swing.JTable TabelaProdutos;
    private javax.swing.JTabbedPane Tabs;
    private javax.swing.JLabel Total;
    private javax.swing.JLabel TotalLabel;
    private javax.swing.JTextField TxtEstoque;
    private javax.swing.JTextField TxtPreco;
    private javax.swing.JTextField TxtProduto;
    private javax.swing.JTextField TxtUserLogin;
    private javax.swing.JPasswordField TxtUserPass;
    private javax.swing.JTextField TxtUsername;
    private javax.swing.JTable VendaTabela;
    private javax.swing.JButton addCliente;
    private javax.swing.JButton addUsuario;
    private javax.swing.JButton addVenda;
    private javax.swing.JButton deleteCliente;
    private javax.swing.JButton deleteUsuario;
    private javax.swing.JButton deleteVenda;
    private javax.swing.JButton editCliente;
    private javax.swing.JButton editUsuario;
    private javax.swing.JButton endVenda;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable tabelaClientes;
    private javax.swing.JTable tabelaUsuarios;
    private javax.swing.JFormattedTextField txtClientBirthday;
    private javax.swing.JTextField txtClientMail;
    private javax.swing.JTextField txtClientName;
    private javax.swing.JTextField txtClientePhone;
    // End of variables declaration//GEN-END:variables
}

// Victor Machado
